NumPy array elements can be accessed using indexing. Below are some of the useful examples:

### Why Vectors are used in Machine Learning

### Why NumPy over Python Regular Arrays

If you assign a single value to a ndarray slice, it is copied across the whole slice

In [4]:
#NumPy Array
import numpy as np
a = np.array([1, 2, 5, 7, 8])
a[1:3] = -1
a

array([ 1, -1, -1,  7,  8])

In [3]:
#Regular Python array
b = [1, 2, 5, 7, 8]
b[1:3] = -1

TypeError: can only assign an iterable

So, it is easier to assign values to a slice of an array in a NumPy array as compared to a normal array wherein it may have to be done using loops.

In [5]:
#NumPy array slice
a = np.array([1, 2, 5, 7, 8])
a_slice = a[1:5]
a_slice[1] = 1000
a
# Original array was modified

array([   1,    2, 1000,    7,    8])

In [6]:
#Python Array
a=[1,2,5,7,8]
b=a[1:5]
b[1]=3
print(a)
print(b)

[1, 2, 5, 7, 8]
[2, 3, 7, 8]


In [8]:
a = np.arange(12).reshape(3, 4)
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [9]:
rows_on = np.array([True, False, True])
a[rows_on , : ]      # Rows 0 and 2, all columns

array([[ 0,  1,  2,  3],
       [ 8,  9, 10, 11]])

An important feature with NumPy arrays is broadcasting.

In [13]:
from numpy import linalg 
coeffs  = np.array([[2, 6], [5, 3]])
depvars = np.array([6, -9])
solution = linalg.solve(coeffs, depvars)
solution

array([-3.,  2.])