### Creating Array

In [7]:
import numpy as np

In [9]:
a = np.array([1,2,3])
print(a)

[1 2 3]


In [13]:
print(a.ndim)

1


In [14]:
type(a)

numpy.ndarray

In [20]:
b = np.array([(1.5,2,3), (4,5,6)], dtype = float)
print(b)

[[1.5 2.  3. ]
 [4.  5.  6. ]]


In [21]:
b.shape

(2, 3)

In [17]:
c = np.array([[(1.5,2,3), (4,5,6)], [(3,2,1), (4,5,6)]],
dtype = float)
print(c)

[[[1.5 2.  3. ]
  [4.  5.  6. ]]

 [[3.  2.  1. ]
  [4.  5.  6. ]]]


In [19]:
c.shape

(2, 2, 3)

### Initial Placeholders

In [22]:
np.zeros((3,4)) #Create an array of zeros

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [23]:
np.ones((2,3,4),dtype=np.int16) # Create an array of ones

array([[[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]],

       [[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]]], dtype=int16)

In [24]:
d = np.arange(10,25,5) #Create an array of evenly spaced values (step value)

In [25]:
d

array([10, 15, 20])

In [26]:
np.linspace(0,2,9) #Create an array of evenly spaced values (number of samples)

array([0.  , 0.25, 0.5 , 0.75, 1.  , 1.25, 1.5 , 1.75, 2.  ])

In [27]:
e = np.full((2,2),7) #Create a constant array

In [28]:
e

array([[7, 7],
       [7, 7]])

In [29]:
f = np.eye(2) #Create a 2X2 identity matrix

In [30]:
f

array([[1., 0.],
       [0., 1.]])

In [33]:
np.random.random((2,2))  #Create an array with random values

array([[0.33083319, 0.47155694],
       [0.46985171, 0.71265345]])

In [32]:
np.empty((3,2)) #Create an empty array

array([[1.5, 2. ],
       [3. , 4. ],
       [5. , 6. ]])

### Data Types

In [35]:
#Signed 64-bit integer types
np.int64

numpy.int64

In [36]:
#Standard double-precision floating point
np.float32

numpy.float32

In [37]:
#Complex numbers represented by 128 floats
np.complex

complex

In [38]:
#Boolean type storing TRUE and FALSE values
np.bool

bool

In [39]:
#Python object type
np.object

object

In [40]:
#Fixed-length unicode type
np.unicode_

numpy.str_

### Inspecting Your Array

In [50]:
b = np.array([(1.5,2,3), (4,5,6)], dtype = float)

In [42]:
b.shape #Array dimensions

(2, 3)

In [43]:
len(b)  #Length of array

2

In [44]:
#Number of array dimensions
b.ndim

2

In [45]:
#Number of array elements
b.size

6

In [46]:
#Data type of array elements
b.dtype

dtype('float64')

In [47]:
#Name of data type
b.dtype.name

'float64'

In [48]:
#Convert an array to a different type
b.astype(int)

array([[1, 2, 3],
       [4, 5, 6]])

### Asking For Help

In [49]:
np.info(np.ndarray.dtype)

Data-type of the array's elements.

Parameters
----------
None

Returns
-------
d : numpy dtype object

See Also
--------
numpy.dtype

Examples
--------
>>> x
array([[0, 1],
       [2, 3]])
>>> x.dtype
dtype('int32')
>>> type(x.dtype)
<type 'numpy.dtype'>


### Arithmetic Operations

In [57]:
a = np.array([1,2,3])
b = np.array([(1.5,2,3), (4,5,6)], dtype = float)
print(a)
b

[1 2 3]


array([[1.5, 2. , 3. ],
       [4. , 5. , 6. ]])

In [59]:
g = a-b #Subtraction
g

array([[-0.5,  0. ,  0. ],
       [-3. , -3. , -3. ]])

In [60]:
np.subtract(a,b) #Subtraction

array([[-0.5,  0. ,  0. ],
       [-3. , -3. , -3. ]])

In [61]:
b + a #Addition

array([[2.5, 4. , 6. ],
       [5. , 7. , 9. ]])

In [62]:
np.add(b,a) #Addition

array([[2.5, 4. , 6. ],
       [5. , 7. , 9. ]])

In [63]:
a / b #Division

array([[0.66666667, 1.        , 1.        ],
       [0.25      , 0.4       , 0.5       ]])

In [64]:
np.divide(a,b) #Division

array([[0.66666667, 1.        , 1.        ],
       [0.25      , 0.4       , 0.5       ]])

In [65]:
a * b #Multiplication

array([[ 1.5,  4. ,  9. ],
       [ 4. , 10. , 18. ]])

In [66]:
np.multiply(a,b) #Multiplication

array([[ 1.5,  4. ,  9. ],
       [ 4. , 10. , 18. ]])

In [67]:
np.exp(b) #Exponentiation

array([[  4.48168907,   7.3890561 ,  20.08553692],
       [ 54.59815003, 148.4131591 , 403.42879349]])

In [68]:
np.sqrt(b)

array([[1.22474487, 1.41421356, 1.73205081],
       [2.        , 2.23606798, 2.44948974]])

In [69]:
np.sin(a) #Print sines of an array

array([0.84147098, 0.90929743, 0.14112001])

In [70]:
np.cos(b)  #Element-wise cosine

array([[ 0.0707372 , -0.41614684, -0.9899925 ],
       [-0.65364362,  0.28366219,  0.96017029]])

In [73]:
np.log(a) #Element-wise natural logarithm

array([0.        , 0.69314718, 1.09861229])

In [74]:
e

array([[7, 7],
       [7, 7]])

In [75]:
f

array([[1., 0.],
       [0., 1.]])

In [72]:
e.dot(f) #Dot product

array([[7., 7.],
       [7., 7.]])

### Comparison

In [76]:
a == b #Element-wise comparison

array([[False,  True,  True],
       [False, False, False]])

In [77]:
a < 2 #Element-wise comparison

array([ True, False, False])

In [78]:
np.array_equal(a, b) #Array-wise comparison

False

### Aggregate Functions

In [80]:

a

array([1, 2, 3])

In [82]:
#Array-wise sum
a.sum()

6

In [83]:
#Array-wise minimum value
a.min()

1

In [86]:
#Maximum value of an array row
a.min(axis = 0)

1

In [88]:
#Cumulative sum of the elements
print(b)
b.cumsum(axis=1)

[[1.5 2.  3. ]
 [4.  5.  6. ]]


array([[ 1.5,  3.5,  6.5],
       [ 4. ,  9. , 15. ]])

In [89]:
a.mean()

2.0

In [92]:
np.std(b)

1.5920810978785667

In [93]:
np.median(b)

3.5

In [94]:
np.corrcoef(a)

1.0

In [95]:
np.mean(a)

2.0

### Copying Arrays

In [97]:
h = a.view()
h

array([1, 2, 3])

In [99]:
np.copy(a)

array([1, 2, 3])

In [100]:
h = a.copy()

### Sorting Arrays

In [102]:
a.sort()
a

array([1, 2, 3])

In [103]:
c.sort(axis=0)

In [104]:
c

array([[[1.5, 2. , 1. ],
        [4. , 5. , 6. ]],

       [[3. , 2. , 3. ],
        [4. , 5. , 6. ]]])

In [105]:
array = np.array([[(1.5,2,3), (4,5,6)], [(3,2,1), (4,5,6)]],
dtype = float)
print(array)

[[[1.5 2.  3. ]
  [4.  5.  6. ]]

 [[3.  2.  1. ]
  [4.  5.  6. ]]]


In [106]:
array.sort(axis=0)

In [107]:
array

array([[[1.5, 2. , 1. ],
        [4. , 5. , 6. ]],

       [[3. , 2. , 3. ],
        [4. , 5. , 6. ]]])

### Subsetting, Slicing, Indexing

In [108]:
a[2]

3

In [109]:
b[1,2]

6.0

In [113]:
a[0:2]

array([1, 2])

In [114]:
b

array([[1.5, 2. , 3. ],
       [4. , 5. , 6. ]])

In [111]:
b[0:2,1]

array([2., 5.])

In [112]:
b[:1] #Select all items at row 0((equivalent to b[0:1, :]))

array([[1.5, 2. , 3. ]])

In [115]:
c[1,...] #Same as [1,:,:]

array([[3., 2., 3.],
       [4., 5., 6.]])

In [116]:
a[ : :-1] #Reversed array a

array([3, 2, 1])

In [117]:
a[a<2]

array([1])

In [120]:
b[[1, 0, 1, 0],[0, 1, 2, 0]] #Select elements (1,0),(0,1),(1,2) and (0,0)

array([4. , 2. , 6. , 1.5])

In [121]:
b

array([[1.5, 2. , 3. ],
       [4. , 5. , 6. ]])

In [119]:
b[[1, 0, 1, 0]][:,[0,1,2,0]]  #Select a subset of the matrix’s rows and columns

array([[4. , 5. , 6. , 4. ],
       [1.5, 2. , 3. , 1.5],
       [4. , 5. , 6. , 4. ],
       [1.5, 2. , 3. , 1.5]])

## Array Manipulation

### Transposing Array

In [122]:
i = np.transpose(b) #Permute array dimensions

In [123]:
i

array([[1.5, 4. ],
       [2. , 5. ],
       [3. , 6. ]])

In [124]:
i.T #Permute array dimensions

array([[1.5, 2. , 3. ],
       [4. , 5. , 6. ]])

### Changing Array Shape

In [125]:
b.ravel() #Flatten the array

array([1.5, 2. , 3. , 4. , 5. , 6. ])

In [128]:
h = g.reshape(3,-2) #Reshape, but don’t change data

In [129]:
h

array([[-0.5,  0. ],
       [ 0. , -3. ],
       [-3. , -3. ]])

In [127]:
g

array([[-0.5,  0. ,  0. ],
       [-3. , -3. , -3. ]])

### Adding/Removing Elements

In [131]:
h = a.view()

In [133]:
np.resize(h,(2,6))

array([[1, 2, 3, 1, 2, 3],
       [1, 2, 3, 1, 2, 3]])

In [134]:
np.append(h,g) #Append items to an array

array([ 1. ,  2. ,  3. , -0.5,  0. ,  0. , -3. , -3. , -3. ])

In [135]:
np.insert(a, 1, 5)

array([1, 5, 2, 3])

In [136]:
a

array([1, 2, 3])

In [137]:
np.delete(a,[1])

array([1, 3])

### Combining Arrays

In [138]:
np.concatenate((a,d),axis=0) #Concatenate arrays

array([ 1,  2,  3, 10, 15, 20])

In [139]:
a


array([1, 2, 3])

In [140]:
d

array([10, 15, 20])

In [141]:
#Stack arrays vertically (row-wise)
np.vstack((a,b))

array([[1. , 2. , 3. ],
       [1.5, 2. , 3. ],
       [4. , 5. , 6. ]])

In [142]:
b

array([[1.5, 2. , 3. ],
       [4. , 5. , 6. ]])

In [143]:
np.hstack((e,f)) #Stack arrays horizontally (column-wise)

array([[7., 7., 1., 0.],
       [7., 7., 0., 1.]])

In [144]:
e

array([[7, 7],
       [7, 7]])

In [145]:
f

array([[1., 0.],
       [0., 1.]])

In [147]:
#Create stacked column-wise arrays
np.column_stack((a,d))

array([[ 1, 10],
       [ 2, 15],
       [ 3, 20]])

In [148]:
np.c_[a,d] #Create stacked column-wise arrays

array([[ 1, 10],
       [ 2, 15],
       [ 3, 20]])

### Splitting Arrays

In [150]:
np.hsplit(a,3) #Split the array horizontally at the 3rd index

[array([1]), array([2]), array([3])]

In [151]:
np.vsplit(c,2) #Split the array vertically at the 2nd index

[array([[[1.5, 2. , 1. ],
         [4. , 5. , 6. ]]]), array([[[3., 2., 3.],
         [4., 5., 6.]]])]